# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
filter = { only_tables = [
  "smart_track.drawings",
  "smart_track.features",
  "smart_track.parts",
  "smart_track.status",
] }
